api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    show_webby: false
    http_cache:
        invalidation:
            enabled: false
            #varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'